# Use older, non-container infrastructure to allow sudo
sudo: required

language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - pypy

env:
  - BUILD_CAPNP=
  - BUILD_CAPNP=true
  - BUILD_CAPNP=true CFLAGS="-DKJ_DEBUG"

# skip testing for pypy + BUILD_CAPNP=false since it's failing in travis for some reason
matrix:
  exclude:
    - python: pypy
      env: BUILD_CAPNP=

compiler: gcc

before_install:
  - buildutils/setup_travis.sh
  - pip install pipenv

install:
  - travis_retry pipenv install

script: py.test test;
