image: ubuntu

install:
  # We need wheel installed to build wheels
  - sh: python -m pip install pipenv
  - sh: python -m pipenv install --dev
  - sh: python -m pipenv install --dev -e .

build: off

test_script:
  - sh: python -m pipenv run pytest

after_test:
  - sh: python -m pipenv run python setup.py bdist_wheel

artifacts:
  - path: dist/*
